<?php
use Illuminate\Support\Facades\Input;
?>
<!doctype html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<title></title>
	<style type="text/css" media="print">
        @page 
        {
            size: auto;   /* auto is the current printer page size */
            margin: 8mm;  /* this affects the margin in the printer settings */
        }

        body 
        {
            margin: 0px;  /* the margin on the content before printing */
        }
    </style>
	</head>
<body>
	<?php 
		$values = Input::All();
		if(isset($values["id"])){
			$total_expenses = 0;
			$total_advance = 0;
			$total_fuel_amount = 0;
			$total_incomes = 0;
			$total = 0.0;
			
			$parentId = -1;
			$tripparticulars_arr = array();
			$parent = \LookupTypeValues::where("name","=","TRIP ADVANCES")->get();
			if(count($parent)>0){
				$parent = $parent[0];
				$parentId = $parent->id;
			}
			$tripparticulars =  \LookupTypeValues::where("parentId","=",$parentId)->where("status", "=", "ACTIVE")->get();
			foreach ($tripparticulars as $tripparticular){
				$tripparticulars_arr[] = $tripparticular->id;
			}
			$select_args = array();
			$select_args[] = "officebranch.name as branchId";
			$select_args[] = "tripparticulars.vehicleId as vehicleId";
			$select_args[] = "tripparticulars.amount as amount";
			$select_args[] = "tripparticulars.date as date";
			$select_args[] = "tripparticulars.remarks as remarks";
			$tripadvances = \TripParticulars::where("tripId","=",$values["id"])->where("tripType","=","LOCAL")->where("status","=","ACTIVE")->whereIn("lookupValueId",$tripparticulars_arr)->leftjoin("officebranch","officebranch.id","=","tripparticulars.branchId")->select($select_args)->get();
			foreach($tripadvances as $tripadvance){
				$total = $total+$tripadvance->amount;
			}
			$total_advance = $total;
			
			$entities = \BusBookings::where("id","=",$values["id"])->get();
			foreach ($entities as $entity){
				$entity["source_date"] = date("d-m-Y",strtotime($entity["source_date"]));
				$entity["dest_date"] = date("d-m-Y",strtotime($entity["dest_date"]));
				if($entity["dest_date"] == "01-01-1970"){
					$entity["dest_date"] = "";
				}
	?>
	<div style="width:200mm;  margin: auto;">
	  	<table width="100%">
			<tr>
				<td align='center' style="color:#8A0808;"><b>NEW MORNING STAR TRAVELS<br/><br/></td>
			</tr>
	  	</table>
	  	<table width="100%">
	  		<tr>
	  			<td style="float: left;">MORNING STRAR TRAVELS</td>
	  			<td style="float: right;">Date : {{date("d-m-Y h:i:sA")}}</td>
	  		</tr>
	  		<tr>
	  			<td style="float: left;">Booking Created By :  {{$entity->createdBy}}</td>
	  			<td style="float: right;">Report Generated By : {{Auth::user()->fullName}}</td>
	  		</tr>
	  		<tr>
	  			<td colspan="1"><div style="margin:10px; text-align: center;font-size: 20px;font-weight: bold;">BUS BOOKING REPORT - MST150900243<br/></div></td>
	  		</tr>
	  		
	  	</table>
	  	<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
	  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">CUSTOMER DETAILS</td></tr>
	  		<tr>
	  			<td>Customer Name </td><td>{{strtoupper($entity["cust_name"])}}</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Phone Number </td><td>{{$entity->cust_phone}}</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Email </td><td>{{($entity["cust_email"])}}</td>
	  		</tr>
	  		<tr>
	  			<td>Customer Address </td><td>{{($entity["cust_address"])}}</td>
	  		</tr>
	  	</table>
	  	<table style="margin: -2px; margin-top: 5px;">
	  		<tr>
	  			<td style="min-width: 375px;float: left;">
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
				  		<tr><td style="text-align: center;background-color: #CBCECB; font-weight: bold;">SOURCE TRIP DETAILS</td></tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->source_start_place}}<hr style="max-width: 90%"/>{{$entity->source_end_place}}</td>
				  		</tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->source_date}},&nbsp;{{$entity->source_time}} </td>
				  		</tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->source_busno}} &nbsp; {{$entity->source_bustype}}(s)</td>
				  		</tr>
				  	</table>
	  			</td>
	  			<td style="min-width: 376px;float: left;">
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
				  		<tr><td style="text-align: center;background-color: #CBCECB; font-weight: bold;">RETURN TRIP DETAILS</td></tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->dest_start_place}}<hr style="max-width: 90%"/>{{$entity->dest_end_place}}</td>
				  		</tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->dest_date}},&nbsp;{{$entity->dest_time}} </td>
				  		</tr>
				  		<tr>
				  			<td style="text-align: center">{{$entity->dest_busno}} &nbsp; {{$entity->dest_bustype}}(s)</td>
				  		</tr>
				  	</table>
	  			</td>
	  		</tr>
	  	</table>
	  	<table style="margin: -2px; margin-top: 5px;">
	  		<tr>
	  			<td style="max-width: 375px;min-width: 375px;float: left;">
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;border-collapse: collapse;">
				  		<tr><td colspan="2" style="text-align: center;background-color: #CBCECB; font-weight: bold;">BOOKING INFO</td></tr>
				  		<tr>
				  			<td>Booking Date </td><td>{{date("d-m-Y",strtotime($entity->booking_date))}}</td>
				  		</tr>
				  		<tr>
				  			<?php 
				  				$branch = OfficeBranch::where("id","=",$entity->booking_branch)->get();
				  				foreach ($branch as $b){
				  					$entity->booking_branch = $b->name;
				  				}
				  			?>
				  			<td>Booking Branch </td><td>{{$entity->booking_branch}}</td>
				  		</tr>
				  		<tr>
				  			<td>Fuel Charge Type </td><td>{{$entity->fuel_charge_type}}</td>
				  		</tr>
				  	</table>
	  			</td>
	  			<td style="min-width: 375px;max-width: 375px;float: left;">
	  				<table width="100%" border='1' cellpadding='5' cellspacing='1' style="border: 1px solid green;text-align:right;border-collapse: collapse;">
				  		<tr><td colspan="2"  style="text-align: center;background-color: #CBCECB; font-weight: bold;">BOOKING COST DETAILS</td></tr>
				  		<tr>
				  			<td>Booking Cost</td><td>{{sprintf('%0.2f', $entity->total_cost)}}</td>
				  		</tr>
				  		<tr>
				  			<td>Driver Mamulu Cost </td><td>{{sprintf('%0.2f', $entity->driver_cost)}}</td>
				  		</tr>
				  		<tr>
				  			<td>Other Cost </td><td>{{sprintf('%0.2f', $entity->other_cost)}}</td>
				  		</tr>
				  		<tr>
				  			<td style="font-weight: bold; color: green" >TOTAL BOOKING COST </td><td>{{sprintf('%0.2f', $entity->total_cost)}}</td>
				  		</tr>
				  		<tr>
				  			<td style="font-weight: bold; color: green" >ADVANCE AMOUNT PAID </td><td>{{sprintf('%0.2f', $total_advance)}}</td>
				  		</tr>
				  		<tr>
				  			<td style="font-weight: bold; color: green" >REMAINING AMOUNT TO BE PAID  </td><td>{{sprintf('%0.2f', ($entity->total_cost-$total_advance))}}</td>
				  		</tr>
				  	</table>
	  			</td>
	  		</tr>
	  	</table>
	  	<div style="margin-top: 120px;">
	  		<span  style="font-weight: bold; color: black;float: left;" >Customer Name & Signature </span>
	  		<span  style="font-weight: bold; color: black;float: right;" >Authorized Signature </span>
	  	</div>
  	</div>
  	<?php 
  		}
	}
	?>
</body>
</html>
